api_platform:
    title: Hello API Platform
    description: 'Welcome to the Hello World API of APIs, powered by API Platform.'
    version: 1.0.0
    show_webby: false

    # Swagger UI.
    enable_swagger_ui: true
    enable_swagger: true
    enable_entrypoint: false
    enable_docs: true
    enable_profiler: true

    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
